server {
    resolver ${NGINX_RESOLVER} valid=30s;

    listen 8080;

    gzip on;
    gzip_min_length 256;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    access_by_lua_block {
        local oidc_enabled = os.getenv("OIDC_ENABLED")
        if oidc_enabled == nil then
            return
        end

        local is_insecure = os.getenv("OIDC_SSL_VERIFY"0 == "no"

        local opts = {
            discovery = os.getenv("OIDC_ISSUER") .. "/.well-known/openid-configuration",
            client_id = os.getenv("OIDC_CLIENT_ID"),
            client_secret = os.getenv("OIDC_CLIENT_SECRET"),
            redirect_uri = os.getenv("OIDC_REDIRECT_URI"),
            ssl_verify = os.getenv("OIDC_SSL_VERIFY"),
        }

        local session_opts = {
            storage = "shm",
            shm_zone = "sessions",
            cookie_http_only = not is_insecure,
            cookie_secure = not is_insecure,
            cookie_same_site = "Lax",
            renew = false,
            secret = os.getenv("OIDC_SESSION_SECRET"),
        }

        local res, err = require("resty.openidc").authenticate(opts, nil, nil, session_opts)
        if err then
            ngx.log(ngx.ERR, err)
            ngx.status = 500
            ngx.say(err)
            ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
        end
    }

    include /etc/nginx/oidc/*.conf;
}
